Option Strict Off
Option Explicit On

Imports System

Namespace Negar.Business
    Public Module PermissionKeys
        Public Const ManageUsers As String = "ManageUsers"
        Public Const ManageBasicUsers As String = "ManageBasicUsers"
        Public Const ManageCompanies As String = "ManageCompanies"
        Public Const ManageFiscalYears As String = "ManageFiscalYears"
        Public Const ManageCompaniesYears As String = "ManageCompaniesYears"
        Public Const SelectCompanyFiscalYear As String = "SelectCompanyFiscalYear"
        Public Const ManageAppThemes As String = "ManageAppThemes"
        Public Const ManageAppMessages As String = "ManageAppMessages"
        Public Const DataMigration As String = "DataMigration"
        Public Const BackupData As String = "BackupData"
        Public Const RestoreData As String = "RestoreData"
        Public Const ManageBusinessShells As String = "ManageBusinessShells"
        Public Const ManageUtilities As String = "ManageUtilities"
        Public Const ViewActivityLog As String = "ViewActivityLog"
        Public Const LockSanad1 As String = "LockSanad1"
        Public Const HideSFSHInSanad As String = "HideSFSHInSanad"
        Public Const SwitchUser As String = "SwitchUser"
        Public Const ChangePassword As String = "ChangePassword"

        ' Accounting detailed permissions
        Public Const AccountingSettings As String = "AccountingSettings"
        Public Const AccountingHeader As String = "AccountingHeader"
        Public Const AccountingShenavar As String = "AccountingShenavar"
        Public Const AccountingEntry As String = "AccountingEntry"
        Public Const AccountingBank As String = "AccountingBank"
        Public Const AccountingBankRecIntro As String = "AccountingBankRecIntro"
        Public Const AccountingBankRecImport As String = "AccountingBankRecImport"
        Public Const AccountingBankRecMatch As String = "AccountingBankRecMatch"
        Public Const AccountingBankRecSuggestions As String = "AccountingBankRecSuggestions"
        Public Const AccountingBalance As String = "AccountingBalance"
        Public Const AccountingTarazShenavar As String = "AccountingTarazShenavar"
        Public Const AccountingLedger As String = "AccountingLedger"
        Public Const AccountingDaftarShenavar As String = "AccountingDaftarShenavar"
        Public Const AccountingReports As String = "AccountingReports"
        Public Const AccountingProfitLoss As String = "AccountingProfitLoss"
        Public Const AccountingBalanceSheet As String = "AccountingBalanceSheet"
        Public Const AccountingAdvancedReports As String = "AccountingAdvancedReports"
        Public Const AccountingChartReports As String = "AccountingChartReports"
        Public Const AccountingCustomReports As String = "AccountingCustomReports"
        Public Const AccountingReportsMenu As String = "AccountingReportsMenu"
        Public Const ManageAccounting As String = "ManageAccounting"

        ' Accounting detailed print/export/action buttons permissions
        Public Const AccountingHeaderNew As String = "AccountingHeaderNew"
        Public Const AccountingHeaderEdit As String = "AccountingHeaderEdit"
        Public Const AccountingHeaderDelete As String = "AccountingHeaderDelete"
        Public Const AccountingShenavarNew As String = "AccountingShenavarNew"
        Public Const AccountingShenavarEdit As String = "AccountingShenavarEdit"
        Public Const AccountingShenavarDelete As String = "AccountingShenavarDelete"
        Public Const AccountingEntryNew As String = "AccountingEntryNew"
        Public Const AccountingEntryEdit As String = "AccountingEntryEdit"
        Public Const AccountingEntryDelete As String = "AccountingEntryDelete"
        Public Const AccountingSanad1PrintDocs As String = "AccountingSanad1PrintDocs"
        Public Const AccountingSanad1PrintJournal As String = "AccountingSanad1PrintJournal"
        Public Const AccountingSanad2PrintVoucher As String = "AccountingSanad2PrintVoucher"
        Public Const AccountingSanadCopy As String = "AccountingSanadCopy"
        Public Const AccountingSanadMerge As String = "AccountingSanadMerge"
        Public Const AccountingSanadSplit As String = "AccountingSanadSplit"
        Public Const AccountingBankRecSelectFile As String = "AccountingBankRecSelectFile"
        Public Const AccountingBankRecSaveData As String = "AccountingBankRecSaveData"
        Public Const AccountingBankRecTransferDesc As String = "AccountingBankRecTransferDesc"
        Public Const AccountingBankRecStatementReport As String = "AccountingBankRecStatementReport"
        Public Const AccountingBankRecExportExcel As String = "AccountingBankRecExportExcel"
        Public Const AccountingTrialPrint As String = "AccountingTrialPrint"
        Public Const AccountingTrialExport As String = "AccountingTrialExport"
        Public Const AccountingLedgerPrint As String = "AccountingLedgerPrint"
        Public Const AccountingLedgerExport As String = "AccountingLedgerExport"
        Public Const AccountingTarazShenavarPrint As String = "AccountingTarazShenavarPrint"
        Public Const AccountingTarazShenavarExport As String = "AccountingTarazShenavarExport"
        Public Const AccountingDaftarShenavarPrint As String = "AccountingDaftarShenavarPrint"
        Public Const AccountingDaftarShenavarExport As String = "AccountingDaftarShenavarExport"
        Public Const AccountingProfitLossSaveSettings As String = "AccountingProfitLossSaveSettings"
        Public Const AccountingProfitLossEditSettings As String = "AccountingProfitLossEditSettings"
        Public Const AccountingProfitLossMapAccounts As String = "AccountingProfitLossMapAccounts"
        Public Const AccountingProfitLossCalculate As String = "AccountingProfitLossCalculate"
        Public Const AccountingProfitLossPrint As String = "AccountingProfitLossPrint"
        Public Const AccountingProfitLossExport As String = "AccountingProfitLossExport"
        Public Const AccountingBalanceSheetSaveSettings As String = "AccountingBalanceSheetSaveSettings"
        Public Const AccountingBalanceSheetEditSettings As String = "AccountingBalanceSheetEditSettings"
        Public Const AccountingBalanceSheetMapAccounts As String = "AccountingBalanceSheetMapAccounts"
        Public Const AccountingBalanceSheetCalculate As String = "AccountingBalanceSheetCalculate"
        Public Const AccountingBalanceSheetPrint As String = "AccountingBalanceSheetPrint"
        Public Const AccountingBalanceSheetExport As String = "AccountingBalanceSheetExport"
        Public Const AccountingCustomReportNew As String = "AccountingCustomReportNew"
        Public Const AccountingCustomReportEdit As String = "AccountingCustomReportEdit"
        Public Const AccountingCustomReportDelete As String = "AccountingCustomReportDelete"
        Public Const AccountingCustomReportPrint As String = "AccountingCustomReportPrint"
        Public Const AccountingCustomReportExport As String = "AccountingCustomReportExport"
        Public Const TradeProductUnits As String = "TradeProductUnits"
        Public Const TradeProductGroups As String = "TradeProductGroups"
        Public Const TradeProducts As String = "TradeProducts"
        Public Const TradeWarehouses As String = "TradeWarehouses"
        Public Const TradePurchase As String = "TradePurchase"
        Public Const TradeSales As String = "TradeSales"
        Public Const TradeRemittance As String = "TradeRemittance"
        Public Const TradeReports As String = "TradeReports"
        Public Const ManageProducts As String = "ManageProducts"
        Public Const ManageWarehouses As String = "ManageWarehouses"
        Public Const ManagePurchases As String = "ManagePurchases"
        Public Const ManageSales As String = "ManageSales"
        Public Const ViewInventory As String = "ViewInventory"
        Public Const ManageTradeWarehouse As String = "ManageTradeWarehouse"
        Public Const ViewReports As String = "ViewReports"

        ' Anbar Edition Modules Permissions
        ' Anbar Mini unique permission keys
        Public Const AnbarMiniModule As String = "AnbarMiniModule"
        Public Const AnbarMiniPos As String = "AnbarMiniPos"
        Public Const AnbarMiniPosNew As String = "AnbarMiniPosNew"
        Public Const AnbarMiniPosEdit As String = "AnbarMiniPosEdit"
        Public Const AnbarMiniPosDelete As String = "AnbarMiniPosDelete"
        Public Const AnbarMiniKharid As String = "AnbarMiniKharid"
        Public Const AnbarMiniKharidNew As String = "AnbarMiniKharidNew"
        Public Const AnbarMiniKharidEdit As String = "AnbarMiniKharidEdit"
        Public Const AnbarMiniKharidDelete As String = "AnbarMiniKharidDelete"
        Public Const AnbarMiniPersons As String = "AnbarMiniPersons"
        Public Const AnbarMiniPersonsNew As String = "AnbarMiniPersonsNew"
        Public Const AnbarMiniPersonsEdit As String = "AnbarMiniPersonsEdit"
        Public Const AnbarMiniPersonsDelete As String = "AnbarMiniPersonsDelete"
        Public Const AnbarMiniExpenses As String = "AnbarMiniExpenses"
        Public Const AnbarMiniExpensesSave As String = "AnbarMiniExpensesSave"
        Public Const AnbarMiniExpensesEdit As String = "AnbarMiniExpensesEdit"
        Public Const AnbarMiniExpensesDelete As String = "AnbarMiniExpensesDelete"
        Public Const AnbarMiniExpenseLedger As String = "AnbarMiniExpenseLedger"
        Public Const AnbarMiniProfitLoss As String = "AnbarMiniProfitLoss"
        Public Const AnbarMiniProducts As String = "AnbarMiniProducts"
        Public Const AnbarMiniProductsNew As String = "AnbarMiniProductsNew"
        Public Const AnbarMiniProductsEdit As String = "AnbarMiniProductsEdit"
        Public Const AnbarMiniProductsDelete As String = "AnbarMiniProductsDelete"
        Public Const AnbarMiniWarehouses As String = "AnbarMiniWarehouses"
        Public Const AnbarMiniWarehousesNew As String = "AnbarMiniWarehousesNew"
        Public Const AnbarMiniWarehousesEdit As String = "AnbarMiniWarehousesEdit"
        Public Const AnbarMiniWarehousesDelete As String = "AnbarMiniWarehousesDelete"
        Public Const AnbarMiniGroups As String = "AnbarMiniGroups"
        Public Const AnbarMiniGroupsNewTop As String = "AnbarMiniGroupsNewTop"
        Public Const AnbarMiniGroupsNew As String = "AnbarMiniGroupsNew"
        Public Const AnbarMiniGroupsEdit As String = "AnbarMiniGroupsEdit"
        Public Const AnbarMiniGroupsDelete As String = "AnbarMiniGroupsDelete"
        Public Const AnbarMiniReports As String = "AnbarMiniReports"
        Public Const AnbarMiniInvStock As String = "AnbarMiniInvStock"
        Public Const AnbarMiniInvStockPrint As String = "AnbarMiniInvStockPrint"
        Public Const AnbarMiniKardex As String = "AnbarMiniKardex"
        Public Const AnbarMiniKardexLoad As String = "AnbarMiniKardexLoad"
        Public Const AnbarMiniKardexPrint As String = "AnbarMiniKardexPrint"
        Public Const AnbarMiniProfitLossRep As String = "AnbarMiniProfitLossRep"
        Public Const AnbarMiniProfitLossLoad As String = "AnbarMiniProfitLossLoad"
        Public Const AnbarMiniProfitLossPrintStatement As String = "AnbarMiniProfitLossPrintStatement"
        Public Const AnbarMiniProfitLossPrintRep As String = "AnbarMiniProfitLossPrintRep"
        Public Const AnbarMiniInventoryCount As String = "AnbarMiniInventoryCount"
        Public Const AnbarMiniInventoryCountGenerate As String = "AnbarMiniInventoryCountGenerate"
        Public Const AnbarMiniInventoryCountPrint As String = "AnbarMiniInventoryCountPrint"
        Public Const AnbarMiniModyan As String = "AnbarMiniModyan"
        Public Const AnbarMiniModyanSend As String = "AnbarMiniModyanSend"
        Public Const AnbarMiniModyanGuide As String = "AnbarMiniModyanGuide"
        Public Const TradeModyanMedium As String = "TradeModyanMedium"
        Public Const TradeModyanBig As String = "TradeModyanBig"
        Public Const TradeModyanKeysSetup As String = "TradeModyanKeysSetup"
        Public Const TradeModyanSendInvoices As String = "TradeModyanSendInvoices"
        Public Const TradeModyanInquiry As String = "TradeModyanInquiry"
        Public Const AnbarMediumModule As String = "AnbarMediumModule"
        Public Const AnbarBigModule As String = "AnbarBigModule"

        ' Payroll permissions
        Public Const PayrollModule As String = "PayrollModule"
        Public Const PayrollPersonnel As String = "PayrollPersonnel"
        Public Const PayrollAttendance As String = "PayrollAttendance"
        Public Const PayrollCalculate As String = "PayrollCalculate"
        Public Const PayrollDiskettes As String = "PayrollDiskettes"
        Public Const PayrollBankFile As String = "PayrollBankFile"
        Public Const PayrollReports As String = "PayrollReports"

        ' Fixed Assets (Amval) permissions
        Public Const AmvalModule As String = "AmvalModule"
        Public Const AmvalAssets As String = "AmvalAssets"
        Public Const AmvalDepreciation As String = "AmvalDepreciation"
        Public Const AmvalTransfers As String = "AmvalTransfers"
        Public Const AmvalInventory As String = "AmvalInventory"
        Public Const AmvalReports As String = "AmvalReports"

        ' Office Automation (AutomationEdari) permissions
        Public Const AutomationModule As String = "AutomationModule"
        Public Const AutomationLetters As String = "AutomationLetters"
        Public Const AutomationInbox As String = "AutomationInbox"
        Public Const AutomationSecretariat As String = "AutomationSecretariat"
        Public Const AutomationReports As String = "AutomationReports"

        ' CRM (Customer Relationship Management) permissions
        Public Const CrmModule As String = "CrmModule"
        Public Const CrmLeads As String = "CrmLeads"
        Public Const CrmOpportunities As String = "CrmOpportunities"
        Public Const CrmActivities As String = "CrmActivities"
        Public Const CrmTickets As String = "CrmTickets"
        Public Const CrmReports As String = "CrmReports"

        ' Advanced Treasury & Cash Flow permissions
        Public Const TreasuryModule As String = "TreasuryModule"
        Public Const TreasuryCashBanks As String = "TreasuryCashBanks"
        Public Const TreasuryChecks As String = "TreasuryChecks"
        Public Const TreasuryLoans As String = "TreasuryLoans"
        Public Const TreasuryCashFlow As String = "TreasuryCashFlow"
        Public Const TreasuryReports As String = "TreasuryReports"

        ' Budgeting & Cost Control permissions
        Public Const BudgetingModule As String = "BudgetingModule"
        Public Const BudgetingItems As String = "BudgetingItems"
        Public Const BudgetingEnforcement As String = "BudgetingEnforcement"
        Public Const BudgetingAmendments As String = "BudgetingAmendments"
        Public Const BudgetingReports As String = "BudgetingReports"

        ' Costing & Production permissions
        Public Const ProductionModule As String = "ProductionModule"
        Public Const ProductionBOM As String = "ProductionBOM"
        Public Const ProductionOrders As String = "ProductionOrders"
        Public Const ProductionCosting As String = "ProductionCosting"
        Public Const ProductionWIP As String = "ProductionWIP"
        Public Const ProductionReports As String = "ProductionReports"

        ' Project & Contract Management permissions
        Public Const ProjectModule As String = "ProjectModule"
        Public Const ProjectProfile As String = "ProjectProfile"
        Public Const ProjectWBS As String = "ProjectWBS"
        Public Const ProjectClaims As String = "ProjectClaims"
        Public Const ProjectGuarantees As String = "ProjectGuarantees"
        Public Const ProjectReports As String = "ProjectReports"

        ' KPI & Performance Management permissions
        Public Const KpiModule As String = "KpiModule"
        Public Const KpiDefinitions As String = "KpiDefinitions"
        Public Const KpiEvaluations As String = "KpiEvaluations"
        Public Const KpiBonuses As String = "KpiBonuses"
        Public Const KpiReports As String = "KpiReports"

        ' CRUD suffixes
        Public Const CanCreate As String = ".CanCreate"
        Public Const CanEdit As String = ".CanEdit"
        Public Const CanDelete As String = ".CanDelete"
        Public Const CanPrint As String = ".CanPrint"
        Public Const CanExport As String = ".CanExport"
    End Module
End Namespace
